---
lighttpd/lighttpd-1.4.35.tar.bz2:
  object_id: a50c25a8-bddc-4a69-a33d-96a90ec6938b
  sha: !binary |-
    M2NmZTdiZDg5NDc0NmExYTI3MjkyOTlmMmZkNzlkODgwNWY0ZTE2ZA==
  size: 665955
elasticsearch/elasticsearch-1.1.2.tar.gz:
  object_id: 6865eb88-dc38-4b32-ace3-4531c7c02694
  sha: !binary |-
    MDQyMDBlYmZjN2YxMmM4Y2QxNDRiNTk5ZmE1ODMyOWIwY2ZhOWQwZQ==
  size: 19891591
kibana/kibana-3.1.0.tar.gz:
  object_id: 788f8a05-cec4-4cca-986e-eeb34f0fdb28
  sha: !binary |-
    ZWZmYzIwYzgzYzBjYjhkNWU4NDRkMjYzNGJkMTg1NGExODU4YmM0Mw==
  size: 1073033
logstash/logstash-1.4.2.tar.gz:
  object_id: 0725e81c-ff0b-43f7-a420-66bee3cde35d
  sha: !binary |-
    ZDU5ZWY1NzljNzYxNGM1ZGY5YmQ2OWNmZGNlMjBlZDM3MWY3MjhmZg==
  size: 85619205
java/jre-7u65-linux-x64.tar.gz:
  object_id: 943d6303-dafb-4073-bc45-46b5210894b1
  sha: !binary |-
    ZGY1MGVhYjI3NzcyNjhkMzViN2NhNDMyMjgxYThlMzgyNzcwNDIwNA==
  size: 47005094
