---
lighttpd/lighttpd-1.4.35.tar.bz2:
  object_id: e3338e34-cc9a-4bf1-9624-70cde9feae13
  sha: !binary |-
    M2NmZTdiZDg5NDc0NmExYTI3MjkyOTlmMmZkNzlkODgwNWY0ZTE2ZA==
  size: 665955
elasticsearch/elasticsearch-1.1.2.tar.gz:
  object_id: bead46d8-a8d3-40d5-baad-a1d35a4875b7
  sha: !binary |-
    MDQyMDBlYmZjN2YxMmM4Y2QxNDRiNTk5ZmE1ODMyOWIwY2ZhOWQwZQ==
  size: 19891591
kibana/kibana-3.1.0.tar.gz:
  object_id: e921bcca-23b5-411c-97cd-236913eeef05
  sha: !binary |-
    ZWZmYzIwYzgzYzBjYjhkNWU4NDRkMjYzNGJkMTg1NGExODU4YmM0Mw==
  size: 1073033
logstash/logstash-1.4.2.tar.gz:
  object_id: 37dd045d-752d-40eb-aa7c-ce36b6d83b69
  sha: !binary |-
    ZDU5ZWY1NzljNzYxNGM1ZGY5YmQ2OWNmZGNlMjBlZDM3MWY3MjhmZg==
  size: 85619205
java/jre-7u65-linux-x64.tar.gz:
  object_id: 21f7449b-e08b-4bb9-aa26-7870919e07b4
  sha: !binary |-
    ZGY1MGVhYjI3NzcyNjhkMzViN2NhNDMyMjgxYThlMzgyNzcwNDIwNA==
  size: 47005094
